# ===========================
# MAIN PARAMETERS
# ===========================
# These are the main parameters you'll want to customize
mode:                 "screen"  # Options: "learn", "screen"
research_interests:   "${projectDir}/config/research_interests.md"
journals_tsv:         "${projectDir}/config/journals.tsv"

metadata_extraction_system_prompt: "${projectDir}/prompts/metadata_extraction.md"
tagging_system_prompt:             "${projectDir}/prompts/tagging.md"
classification_system_prompt:      "${projectDir}/prompts/classification.md"

# Zotero Configuration
zotero_user_id:       "1508765"

# PostgreSQL Configuration
# Set the password as a Nextflow secret:
#   nextflow secrets set PGPASSWORD "npg_fazJWkPw8BL4"
# The connection string will use it at runtime

# ===========================
# OTHER PARAMETERS
# ===========================
# ===========================
# Backend Configuration
# ===========================
from:                      "articles_json"
from_json_input:           "articles.json"
# from_duckdb_input:         "papers_please.duckdb"
# from_pg_user:              "neondb_owner"
# from_pg_host:              "ep-lingering-tree-a4l7zn7a-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
from_zotero_collection_id: "JP3SY2UN"
from_zotero_library_type:  "user"

to:                        "articles_json"
# to_json_outdir:            "./results"
to_pg_user:                "neondb_owner"
to_pg_host:                "ep-lingering-tree-a4l7zn7a-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
# to_zotero_collection_id:   "U3T98NSQ"
# to_zotero_library_type:    "user"

# days_back: 8

# ===========================
# LLM Models Configuration
# ===========================
# batch_size:                       10
# metadata_extraction_model:        "gemini-2.5-flash-lite"
# tagging_model:                    "gemini-2.5-flash-lite"
# embedding_model:                  "gemini-embedding-001"
# classification_model:             "gemini-2.5-flash-lite"

# ===========================
# Others
# ===========================
# debug: false
